services:
  db:
    image: postgres:16
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  diesel-cli:
    container_name: diesel-cli
    build:
      context: ./
      dockerfile: ./Dockerfile.Diesel
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
    volumes:
      - ./:/app
      - diesel-cli-target:/diesel/target
    depends_on:
      - db

volumes:
  db-data:
  diesel-cli-target:

